---
study: testStudy

ended:
  startGamePicture:

conditions:
  Condition1:
    item2:
    startGameBlock:
    exampleRandom:
  Condition2:
    item2:
    startGameBlock:
    exampleStimuli:

blocks:
  startGameBlock:
    startGamePicture:
    startGameVideo:
  exampleRandom:
    item1:
    item2:
    shuffle: true
  exampleStimuli:
    item3:
    item1:
    pickRandom: true

stimuli:
  startGameVideo:
    type: movie
    parameters:
      # todo make assets lookup more intuitive. no ../ - this will be hosted remotely so should be simple, then loaded locally into db
      filename: '../../../assets/sample/video1.mp4'
      responses:
        one:
          shape: rect
          location: "161, 646, 250, 740"
  item1:
    type: movie
    parameters:
      filename: '../../../assets/sample/video1.mp4'
      responses:
        one:
          shape: rect
          location: "161, 646, 250, 740"
  item2:
    type: movie
    parameters:
      filename: '../../../assets/sample/video2.mp4'
      responses:
        one:
          shape: rect
          location: "161, 646, 250, 740"
          action: item3
        two:
          shape: rect
          location: "282, 646, 370, 740"
          action: item3
  item3:
    type: picture
    parameters:
      filename: '../../../assets/sample/image1.png'
      responses:
        one:
          shape: rect
          location: "0, 0, 100, 100"
  startGamePicture:
    type: picture
    parameters:
      filename: '../../../assets/sample/start.jpeg'
      responses:
        start:
          shape: rect
          location: "0, 0, 5000, 5000"

forms:
  startForm:
    type: form
    parameters:
      questions:
        id:
          type: text
          title: "Participant ID"
        gender:
          type: dropdown
          options: "female, male, other"
          title: "Participant Gender"

# TODO
# slider scales
# reaction times
# circular buttons
