---
study: testStudy

ended:
  endedPicture:
    type: picture
    parameters:
      filename: '../../../assets/sample/end.png'
      responses:
        end:
          shape: rect
          location: "0, 0, 5000, 5000"

conditions:
  Condition1:
    forms:
    startGameBlock:
    exampleRandom:
  Condition2:
    forms:
    startGameBlock:
    exampleStimuli:

blocks:
  startGameBlock:
    startGamePicture:
    startGameVideo:
  exampleRandom:
    item2:
    item8:
    shuffle: true
  exampleStimuli:
    item3:
    item1:
    pickOne: true
  anotherBlock:
    item6:
  forms:
    startForm:
      type: form
      parameters:
        questions:
          id:
            type: text
            title: "Participant ID"
          gender:
            type: dropdown
            options: "female, male, other"
            title: "Participant Gender"


stimuli:
  startGameVideo:
    type: movie
    parameters:
      # todo make assets lookup more intuitive. no ../ - this will be hosted remotely so should be simple, then loaded locally into db
      filename: '../../../assets/sample/video1.mp4'
      responses:
        one:
          shape: rect
          location: "161, 646, 250, 740"
  item1:
    type: movie
    parameters:
      filename: '../../../assets/sample/video1.mp4'
      responses:
        one:
          shape: rect
          location: "161, 646, 250, 740"
  item2:
    type: movie
    parameters:
      filename: '../../../assets/sample/video2.mp4'
      responses:
        one:
          shape: rect
          location: "161, 646, 250, 740"
          action: anotherBlock
        two:
          shape: rect
          location: "282, 646, 370, 740"
          action: item6
  item3:
    type: picture
    parameters:
      filename: '../../../assets/sample/image1.png'
      responses:
        four:
          shape: rect
          location: "0, 0, 500, 500"
          action: item7
  item6:
    type: picture
    parameters:
      filename: '../../../assets/sample/image1.png'
      responses:
        five:
          shape: rect
          location: "0, 0, 500, 500"
          action: item9
  item7:
    type: picture
    parameters:
      filename: '../../../assets/sample/image2.png'
      responses:
        five:
          shape: rect
          location: "0, 0, 500, 500"
  item8:
    type: picture
    parameters:
      filename: '../../../assets/sample/image3.png'
      responses:
        five:
          shape: rect
          location: "0, 0, 500, 500"
  item9:
    type: picture
    parameters:
      filename: '../../../assets/sample/image4.png'
      responses:
        five:
          shape: rect
          location: "0, 0, 500, 500"
  startGamePicture:
    type: picture
    parameters:
      filename: '../../../assets/sample/start.jpeg'

# TODO
# slider scales
# reaction times
# circular buttons
